apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
  name: cosign
  labels:
    app.kubernetes.io/version: 0.1.0
spec:
  description: >-
    These tasks make it possible to use cosign within your Tekton pipelines
    cosign is a tool for signing and verifying software artifacts.
  params:
    - name: cosignkey
      type: string
    - name: IMAGE
      type: string
    - name: IMAGE_TAG
      type: string
    - name: NAMESPACE
      type: string
  results:
    - description: The email from the certificate common name in JSON format
      name: email
  steps:
    - env:
        - name: COSIGN_EXPERIMENTAL
          value: "1"
      image: "gcr.io/projectsigstore/cosign:v1.13.1"
      name: cosign
      resources: {}
      script: >
        #!/busybox/env /busybox/sh

        [[ "$(workspaces.dockerconfig.bound)" == "true" ]] && export DOCKER_CONFIG="$(workspaces.dockerconfig.path)"

        CMD="cosign sign --key k8s://$(params.NAMESPACE)/$(params.cosignkey) $(params.IMAGE):$(params.IMAGE_TAG)"

        echo "${CMD}"

        ERR_MSG="Failed to sign $(params.IMAGE):$(params.IMAGE_TAG)"

        ${CMD} &> result

        err=$?

        cat result

        if [[ ${err} -ne 0 ]]; then
          echo "${ERR_MSG}"
          exit 1
        fi
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
    - name: dockerconfig
