---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-updater
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: Image Build
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: image-updater
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    Image update task updates the imagetag for the argoapp
    passed as parameter in the git repository.

  params:
  - name: IMAGE_TAG
    description: Reference of the tag that will be updated in git.
  - name: ARGOCD_NAMESPACE
    description: 
#  - name: KUBECONFIG_FILE
#    description:
#    default: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  - name: APP_NAME
    description: Name of the application that will get its image updated.
  steps:
  - name: update-image-on-git
    image: quay.io/mavazque/argocd-image-updater:manual-strategy
    script: |
      argocd-image-updater run --argocd-namespace $(params.ARGOCD_NAMESPACE) --once --match-application-name $(params.APP_NAME) --warmup-cache=false --metrics-port=0 --manual-tag-value $(params.IMAGE_TAG)
