---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-build-pipeline
spec:
  params:
  - name: git-revision
  - name: git-commit-message
  - name: git-repo-url
  - name: git-repo-name
  - name: content-type
  - name: pusher-name
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        pipeline.openshift.io/started-by: kube:admin
        tekton.dev/displayName: build-pipeline
        tekton.dev/pipelines.minVersion: 0.17.0
        tekton.dev/platforms: linux/amd64
        tekton.dev/tags: app-build
      generateName: build-pipeline-
      labels:
        app.kubernetes.io/version: "0.1"
        tekton.dev/pipeline: build-pipeline
      namespace: rhte22-devsecops-app-ci
    spec:
      params:
      - name: APP_IMAGE
        value: quay.io/mavazque/rhte22-devsecops-app
      - name: APP_IMAGE_TAG
        value: $(tt.params.git-revision)
      - name: SOURCE_URL
        value: https://github.com/ocp-tigers/rhte22-devsecops-app.git
      - name: SOURCE_REFERENCE
        value: $(tt.params.git-revision)
      - name: NAMESPACE
        value: rhte22-devsecops-app-ci
      - name: ARGOCD_NAMESPACE
        value: openshift-gitops
      - name: ARGOCD_APP_NAME
        value: rhte22-devsecops-app-dev
      pipelineRef:
        name: build-pipeline
      resources: []
      workspaces:
      - name: source-ws
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
#            storageClassName: fs-lso
            volumeMode: Filesystem
      - name: dockerconfig-ws
        secret:
          secretName: quay-user-pass
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-build-pipeline
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    interceptors:
      - name: "Validate this is a push to main"
        ref:
          name: "cel"
        params:
        - name: "filter"
          value: "body.ref.startsWith('refs/heads/main')"
      - name: "Validate GitHub payload and filter on eventType"
        ref:
          name: "github"
        params:
        - name: "secretRef"
          value: 
            secretName: webhook-secret
            secretKey: secret
        - name: "eventTypes"
          value: ["push"]
    template:
      ref: trigger-template-build-pipeline
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: event-listener-build-pipeline
  name: el-build-pipeline
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-event-listener-build-pipeline
    weight: 100
  wildcardPolicy: None
