apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
namespace: demo-devsecops-app-prod
bases:
- ../bases/
resources:
- namespace.yaml
- route.yaml
images:
- name: quay.io/mavazque/demo-devsecops-app
  newTag: manualhacked
