apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-devsecops-app
spec:
  host: demo-devsecops-prod.apps.demo.mavazque.sysdeseng.com
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: "Service"
    name: demo-devsecops-app
    weight: 100
