---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-updater-argoapps-viewer
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: rhte22-devsecops-app-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
